# Generated by Django 4.0.3 on 2024-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0002_naverastro_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverastro',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
