# Generated by Django 4.0.3 on 2024-04-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0004_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
