# Generated by Django 4.0.3 on 2024-04-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0005_alter_sources_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sources',
        ),
    ]
