# Generated by Django 4.0.3 on 2024-05-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0007_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverBiochemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(blank=True, null=True)),
                ('eng', models.TextField(blank=True, null=True)),
                ('simple_sense', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'naver_biochemi',
                'managed': True,
            },
        ),
    ]
