# Generated by Django 4.0.3 on 2024-05-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0008_naverbiochemi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naverbiochemi',
            options={'managed': False},
        ),
    ]
