# Generated by Django 4.0.3 on 2024-05-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0009_alter_naverbiochemi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naverbiochemi',
            options={'managed': True},
        ),
    ]
