# Generated by Django 4.0.3 on 2024-07-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0010_alter_naverbiochemi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverBotany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('term', models.TextField(blank=True, null=True)),
                ('eng', models.TextField(blank=True, null=True)),
                ('simple_sense', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'naver_botany',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='naverbiochemi',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
