# Generated by Django 4.0.3 on 2024-07-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0011_naverbotany_alter_naverbiochemi_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaverBotany',
        ),
    ]
