# Generated by Django 4.0.3 on 2024-07-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0013_naverbotany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naverbotany',
            options={'managed': True},
        ),
    ]
