# Generated by Django 4.0.3 on 2024-07-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0020_sources_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sources',
        ),
    ]
