# Generated by Django 4.0.3 on 2024-07-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0021_delete_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('code', models.TextField(blank=True, null=True)),
                ('uri', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sources',
                'managed': True,
            },
        ),
    ]
