# Generated by Django 4.0.3 on 2024-07-31 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0043_naversaju'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaverSaju',
        ),
    ]
