# Generated by Django 4.0.3 on 2024-08-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0051_naverdisease_navermedibody_naverpharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
