# Generated by Django 4.0.3 on 2024-08-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0054_mirrorarch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirrorarch',
            old_name='simple_sense',
            new_name='simpleEx',
        ),
    ]
