# Generated by Django 4.0.3 on 2024-08-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southterms', '0055_rename_simple_sense_mirrorarch_simpleex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirrorarch',
            old_name='hanja',
            new_name='hanJa',
        ),
    ]
